---
  - name: add ambari-repo
    get_url: url={{ ambari_repo }} dest=/etc/yum.repos.d/ambari.repo

  - name: install ambari
    yum: name=ambari-server state=present

  - name: configure ambari-server
    command: /usr/sbin/ambari-server setup -s
