---
  - name: install libselinux-python
    yum: name=libselinux-python state=present
  - name: copy hosts
    copy: src=hosts dest=/etc/hosts
  - name: switch off selinux
    lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=disabled
  - name: switch off iptables
    service: name=iptables state=stopped enabled=off
  - name: install java
    yum: name=java-1.7.0-openjdk state=present
  - name: configure java
    copy: src=java.sh dest=/etc/profile.d/java.sh
